version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn farmsetu.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - ./.env.prod

    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=farmsetu
      - POSTGRES_PASSWORD=farmsetu
      - POSTGRES_DB=farmsetu

    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - '1337:80'
    depends_on:
      - web

volumes:
    postgres_data:
    static_volume: