# Generated by Django 4.0.3 on 2022-03-21 04:55

import django.core.validators
from django.db import migrations, models
import farmsetu.core_lib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.CharField(db_index=True, default=farmsetu.core_lib.CoreUtils.get_bson_object_id, max_length=24, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
            ],
        ),
    ]
